-- Add Bunny CDN and SMTP settings per school
ALTER TABLE school_settings
  ADD COLUMN IF NOT EXISTS bunny_cdn_api_key VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bunny_cdn_storage_zone VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bunny_cdn_pull_zone VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bunny_cdn_storage_zone_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_from_email VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN NOT NULL DEFAULT TRUE;
