-- Add subscription and limit columns to schools table
ALTER TABLE schools ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(20) NOT NULL DEFAULT 'free';
ALTER TABLE schools ADD COLUMN IF NOT EXISTS subscription_expires_at TIMESTAMPTZ;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_students INTEGER NOT NULL DEFAULT 25;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_staff INTEGER NOT NULL DEFAULT 5;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_classes INTEGER NOT NULL DEFAULT 3;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS max_branches INTEGER NOT NULL DEFAULT 1;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMPTZ;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS is_trial BOOLEAN NOT NULL DEFAULT TRUE;
